# Voluntary Task 2

Task: Implement a boosted decision tree for the auto_mpg data employing AdaBoost. Implement a radnom forest classifier for employing RandomForestClassifier. Compare the prediction results of both models for different training data subsets and parameters of the learning methods.

In [23]:
# Do not change
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

import seaborn as sns

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df1 = pd.read_csv("auto-mpg.csv")
df1.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [3]:
df2 = pd.DataFrame(df1)
print (df2.describe())
print (df2.dtypes)

              mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000  
mpg             float64
cylinders         int

In [4]:
df2['cylinders'] = df2['cylinders'].astype(float)
#df2['cylinders'].dtypes
df2 ['horsepower'] = pd.to_numeric(df2['horsepower'], errors='coerce')
df2 = df2.replace(np.nan, 0, regex=True)
#df2['horsepower'].dtypes
df2['weight'] = df2['weight'].astype(float)
#df2['weight'].dtypes
df2['model year'] = df2['model year'].astype(float)
#df2['model year'].dtypes
df2['origin'] = df2['origin'].astype(float)
#df2['origin'].dtypes
df3 = df2.drop(['car name'], axis = 1)
df3.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0        8.0         307.0       130.0  3504.0          12.0   
1  15.0        8.0         350.0       165.0  3693.0          11.5   
2  18.0        8.0         318.0       150.0  3436.0          11.0   
3  16.0        8.0         304.0       150.0  3433.0          12.0   
4  17.0        8.0         302.0       140.0  3449.0          10.5   

   model year  origin  
0        70.0     1.0  
1        70.0     1.0  
2        70.0     1.0  
3        70.0     1.0  
4        70.0     1.0

The dataset is here being split into two sub datasets on which Adaboost and Random Forest classifier is employed

In [17]:
subset1=df3.sample(frac=0.5,random_state=100)
subset1

mpg  cylinders  displacement  horsepower  weight  acceleration  \
326  43.4        4.0          90.0        48.0  2335.0          23.7   
54   35.0        4.0          72.0        69.0  1613.0          18.0   
78   21.0        4.0         120.0        87.0  2979.0          19.5   
169  20.0        6.0         232.0       100.0  2914.0          16.0   
368  27.0        4.0         112.0        88.0  2640.0          18.6   
..    ...        ...           ...         ...     ...           ...   
175  29.0        4.0          90.0        70.0  1937.0          14.0   
337  32.4        4.0         107.0        72.0  2290.0          17.0   
329  44.6        4.0          91.0        67.0  1850.0          13.8   
291  19.2        8.0         267.0       125.0  3605.0          15.0   
201  18.5        6.0         250.0       110.0  3645.0          16.2   

     model year  origin  
326        80.0     2.0  
54         71.0     3.0  
78         72.0     2.0  
169        75.0     1.0  
368        82.0     1.0  
..          ...     ...  
175        75.0     2.0  
337        80.0     3.0  
329        80.0     3.0  
291        79.0     1.0  
201        76.0     1.0  

[199 rows x 8 columns]

In [18]:
subset2=df3.drop(subset1.index)
subset2

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0        8.0         307.0       130.0  3504.0          12.0   
2    18.0        8.0         318.0       150.0  3436.0          11.0   
4    17.0        8.0         302.0       140.0  3449.0          10.5   
8    14.0        8.0         455.0       225.0  4425.0          10.0   
9    15.0        8.0         390.0       190.0  3850.0           8.5   
..    ...        ...           ...         ...     ...           ...   
390  32.0        4.0         144.0        96.0  2665.0          13.9   
393  27.0        4.0         140.0        86.0  2790.0          15.6   
394  44.0        4.0          97.0        52.0  2130.0          24.6   
395  32.0        4.0         135.0        84.0  2295.0          11.6   
396  28.0        4.0         120.0        79.0  2625.0          18.6   

     model year  origin  
0          70.0     1.0  
2          70.0     1.0  
4          70.0     1.0  
8          70.0     1.0  
9          70.0     1.0  
..          ...     ...  
390        82.0     3.0  
393        82.0     1.0  
394        82.0     2.0  
395        82.0     1.0  
396        82.0     1.0  

[199 rows x 8 columns]

Splitting the subset 1 ito training data and test data

In [39]:
x1 = subset1.drop(['origin'], axis = 1)
y1 = subset1["origin"]

x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.3)

Employing Adaboost

In [40]:
Ada1 = AdaBoostClassifier(n_estimators=100, random_state=0)
Ada1.fit(x1_train, y1_train)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [47]:
y1_pred1 = Ada1.predict(x1_test)
y1_pred1

array([3., 1., 3., 1., 1., 2., 3., 1., 3., 1., 1., 3., 3., 3., 1., 3., 1.,
       3., 1., 1., 2., 3., 1., 1., 3., 3., 1., 1., 3., 1., 1., 1., 3., 3.,
       3., 1., 1., 1., 1., 3., 1., 3., 3., 3., 1., 3., 1., 3., 1., 1., 3.,
       2., 1., 3., 1., 3., 1., 3., 1., 3.])

In [46]:
Ada1.score(x1_train, y1_train)

0.9136690647482014

Employing Random Forest

In [60]:
RFC1 = RandomForestClassifier(max_depth=2, random_state=0)
RFC1.fit(x1_train, y1_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [61]:
y1_pred2 = RFC1.predict(x1_test)
y1_pred2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 3., 1.,
       1., 1., 1., 1., 1., 3., 1., 3., 3., 1., 3., 1., 3., 1., 3., 3., 1.,
       1., 1., 1., 1., 3., 3., 1., 1., 3., 1., 1., 1., 3., 1., 1., 3., 3.,
       3., 1., 3., 1., 1., 1., 1., 1., 1.])

In [62]:
RFC1.score(x1_train, y1_train)

0.7697841726618705

Splitting the subset 2 into training data and test data

In [50]:
x2 = subset2.drop(['origin'], axis = 1)
y2 = subset2["origin"]

In [56]:
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, test_size = 0.6)

In [57]:
Ada2 = AdaBoostClassifier(n_estimators=100, random_state=0)
Ada2.fit(x2_train, y2_train)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [58]:
y2_pred1 = Ada1.predict(x2_test)
y2_pred1

array([3., 3., 1., 1., 1., 3., 1., 1., 3., 1., 1., 3., 1., 1., 1., 3., 2.,
       1., 1., 3., 3., 1., 1., 1., 1., 3., 3., 2., 1., 2., 1., 1., 1., 3.,
       3., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 3., 3., 2., 1., 3., 3.,
       3., 1., 1., 3., 1., 1., 1., 3., 3., 1., 1., 3., 3., 1., 1., 1., 1.,
       3., 1., 1., 3., 3., 3., 1., 1., 1., 1., 3., 3., 1., 3., 1., 1., 1.,
       1., 1., 1., 3., 3., 1., 3., 1., 3., 2., 1., 1., 1., 1., 3., 1., 1.,
       1., 3., 1., 1., 1., 1., 3., 1., 2., 1., 2., 1., 1., 3., 1., 1., 1.,
       3.])

In [59]:
Ada2.score(x2_train, y2_train)

0.9493670886075949

In [70]:
RFC2 = RandomForestClassifier(max_depth=2, random_state=0)
RFC2.fit(x2_train, y2_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [71]:
y1_pred2 = RFC1.predict(x2_test)
y1_pred2

array([1., 3., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 3., 1., 1., 3., 1.,
       3., 1., 3., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 3.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 3., 3., 1., 1., 3.,
       3., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 3., 3., 1., 1., 1., 1.,
       3., 1., 1., 3., 1., 3., 1., 3., 1., 1., 3., 1., 1., 3., 1., 1., 1.,
       1., 1., 1., 3., 3., 1., 1., 1., 1., 1., 3., 1., 1., 3., 3., 3., 3.,
       1., 3., 1., 1., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [72]:
RFC2.score(x2_train, y2_train)

0.8481012658227848

In [83]:
RFC2 = RandomForestClassifier(max_depth=3,min_samples_split=3, random_state=0)
RFC2.fit(x2_train, y2_train)

RFC2.score(x2_train, y2_train)

0.9113924050632911

It is observed from changing the parameters that the accuracy can be enhanced